name: Lint

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

env:
  FOUNDRY_PROFILE: ci

jobs:
  formatter:
    strategy:
      fail-fast: true

    name: Check with formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install prettier
        run: |
          yarn global add prettier

      - name: Check format with Forge
        run: |
          # `forge fmt` bug causing error in this file
          rm src/utilities/TransferHelper.sol
          forge --version
          forge fmt --check src
          forge fmt --check test

      - name: Check format with prettier
        run: |
          prettier --check .
