name: Test

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-foundry:
    strategy:
      fail-fast: true

    name: Test with Foundry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node modules
        run: |
          yarn install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

  test-hardhat:
    strategy:
      fail-fast: true

    name: Test with Hardhat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node modules
        run: |
          yarn install

      - name: Run Hardhat build
        run: |
          yarn hardhat compile
        id: build

      - name: Run Hardhat tests
        run: |
          yarn hardhat test
        id: test
